package com.amobilepayment.demo.Utils;

import AmpBaseInterface.AmpBaseInterface;

public class InternalConfig {

    public static boolean IsAdminLocked() {
        boolean flag = false;
        String data = "N";//AmpBaseInterface.GetCfgData("TERMINAL.PASSWORDOPTION.PASSINFO.PRCSSR.LOCK");
        if("Y".equals(data)) flag = true;
        return flag;
    }

    //1 TERMINAL PARAMETERS
    public final static String CFGPATH_APPLICATION_NAME_FULL = "APPLICATION.NAME.FULL";
    public final static String CFGPATH_APPLICATION_NAME_SHORT = "APPLICATION.NAME.SHORT";
    public final static String CFGPATH_APPLICATION_NAME_TMS	= "APPLICATION.NAME.TMS";

    // Configurable Desktop Items
    public final static String CFGPATH_TERMINAL_DESKTOP_COUNT = "TERMINAL.DESKTOP.COUNT";
    public final static String CFGPATH_TERMINAL_DESKTOP_TRANS = "TERMINAL.DESKTOP.TRANSACTION._%d";

    // Help Contact Info
    public final static String CFGPATH_TERMINAL_HELP_CONTACT = "TERMINAL.HELP.CONTACT";
    public final static String CFGPATH_TERMINAL_HELP_TELNO = "TERMINAL.HELP.TELNO";
    public final static String CFGPATH_TERMINAL_HELP_EMAIL = "TERMINAL.HELP.EMAIL";

    // Password Options
    public final static String CFGPATH_TERMINAL_PWD = "TERMINAL.PASSWORDOPTION";
    public final static String CFGPATH_TERMINAL_PWD_ADMINPASS_MERCHANT = "TERMINAL.PASSWORDOPTION.ADMINPASS.MERCHANT";
    public final static String CFGPATH_TERMINAL_PWD_ADMINPASS_PROCESSOR = "TERMINAL.PASSWORDOPTION.ADMINPASS.PROCESSOR";

    public final static String CFGPATH_TERMINAL_PWD_ADMIN_DAYSEXP = "TERMINAL.PASSWORDOPTION.PASSINFO.DAYSTOEXPIRE";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_HISTNUM = "TERMINAL.PASSWORDOPTION.PASSINFO.HISTORYNUM";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_LOCKTIME = "TERMINAL.PASSWORDOPTION.PASSINFO.LOCKTIME";

    // Merchant Password Options
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_MERCHANT_INIT = "TERMINAL.PASSWORDOPTION.PASSINFO.MRCHNT.INIT";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_MERCHANT_EXP = "TERMINAL.PASSWORDOPTION.PASSINFO.MRCHNT.EXPIRE";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_MERCHANT_RETRY = "TERMINAL.PASSWORDOPTION.PASSINFO.MRCHNT.RETRY";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_MERCHANT_LOCK = "TERMINAL.PASSWORDOPTION.PASSINFO.MRCHNT.LOCK";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_MERCHANT_UNLOCKTIME = "TERMINAL.PASSWORDOPTION.PASSINFO.MRCHNT.UNLOCKTIME";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_MERCHANT_UNLOCKDATE = "TERMINAL.PASSWORDOPTION.PASSINFO.MRCHNT.UNLOCKDATE";

    // Processor Password Options
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_PROCESSOR_INIT = "TERMINAL.PASSWORDOPTION.PASSINFO.PRCSSR.INIT";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_PROCESSOR_EXP = "TERMINAL.PASSWORDOPTION.PASSINFO.PRCSSR.EXPIRE";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_PROCESSOR_RETRY = "TERMINAL.PASSWORDOPTION.PASSINFO.PRCSSR.RETRY";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_PROCESSOR_LOCK = "TERMINAL.PASSWORDOPTION.PASSINFO.PRCSSR.LOCK";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_PROCESSOR_UNLOCKTIME = "TERMINAL.PASSWORDOPTION.PASSINFO.PRCSSR.UNLOCKTIME";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_PROCESSOR_UNLOCKDATE = "TERMINAL.PASSWORDOPTION.PASSINFO.PRCSSR.UNLOCKDATE";

    public final static String CFGPATH_TERMINAL_PWD_ADMIN_MERCHANT_PHIST = "TERMINAL.PASSWORDOPTION.PASSINFO.MRCHNT.P_%d";
    public final static String CFGPATH_TERMINAL_PWD_ADMIN_PROCESSOR_PHIST = "TERMINAL.PASSWORDOPTION.PASSINFO.PRCSSR.P_%d";

    public final static String CFGPATH_TERMINAL_PWD_SUPER				= "TERMINAL.PASSWORDOPTION.SUPERPASS";
    public final static String CFGPATH_TERMINAL_PWD_PWOVERRIDE			= "TERMINAL.PASSWORDOPTION.PWOVERRIDE";
    public final static String CFGPATH_TERMINAL_PWD_OPERATOR			= "TERMINAL.PASSWORDOPTION.OPERATORPASS";
    public final static String CFGPATH_TERMINAL_PWD_MENU_TRANS			= "TERMINAL.PASSWORDOPTION.MENU.TRANSACTION";
    public final static String CFGPATH_TERMINAL_PWD_MENU_EODTRANS		= "TERMINAL.PASSWORDOPTION.MENU.EODTRANSACTION";
    public final static String CFGPATH_TERMINAL_PWD_MENU_TRANSRECALL	= "TERMINAL.PASSWORDOPTION.MENU.TRANSRECALL";
    public final static String CFGPATH_TERMINAL_PWD_MENU_REPRINT		= "TERMINAL.PASSWORDOPTION.MENU.REPRINT";
    public final static String CFGPATH_TERMINAL_PWD_MENU_REPORT		= "TERMINAL.PASSWORDOPTION.MENU.REPORT";
    public final static String CFGPATH_TERMINAL_PWD_MENU_DEVICESETTING	= "TERMINAL.PASSWORDOPTION.MENU.DEVICESETTING";
    public final static String CFGPATH_TERMINAL_PWD_MENU_COMMUNITY		= "TERMINAL.PASSWORDOPTION.MENU.COMMUNITY";
    public final static String CFGPATH_TERMINAL_PWD_MENU_ADMIN			= "TERMINAL.PASSWORDOPTION.MENU.ADMIN";
    public final static String CFGPATH_TERMINAL_PWD_MENU_PROCESSOR		= "TERMINAL.PASSWORDOPTION.MENU.PROCESSOR";
    public final static String CFGPATH_TERMINAL_PWD_TRX_VOID			= "TERMINAL.PASSWORDOPTION.TRX.VOID";
    public final static String CFGPATH_TERMINAL_PWD_TRX_REFUND			= "TERMINAL.PASSWORDOPTION.TRX.REFUND";
    public final static String CFGPATH_TERMINAL_PWD_TRX_ADJUST			= "TERMINAL.PASSWORDOPTION.TRX.ADJUST";
    public final static String CFGPATH_TERMINAL_PWD_TRX_OFFLINE		= "TERMINAL.PASSWORDOPTION.TRX.OFFLINE";
    public final static String CFGPATH_TERMINAL_PWD_TRX_BATCHCLOSE		= "TERMINAL.PASSWORDOPTION.TRX.BATCHCLOSE";
    public final static String CFGPATH_TERMINAL_PWD_TRX_CASHADV		= "TERMINAL.PASSWORDOPTION.TRX.CASHADV";
    public final static String CFGPATH_TERMINAL_PWD_TRX_SALE			= "TERMINAL.PASSWORDOPTION.TRX.SALE";
    public final static String CFGPATH_TERMINAL_PWD_TRX_PREAUTH		= "TERMINAL.PASSWORDOPTION.TRX.PREAUTH";
    public final static String CFGPATH_TERMINAL_PWD_TRX_COMPLETION		= "TERMINAL.PASSWORDOPTION.TRX.COMPLETION";
    public final static String CFGPATH_TERMINAL_PWD_TRX_EBT			= "TERMINAL.PASSWORDOPTION.TRX.EBT";
    public final static String CFGPATH_TERMINAL_PWD_TRX_INCREMENTAL	= "TERMINAL.PASSWORDOPTION.TRX.INCREMENTAL";
    public final static String CFGPATH_TERMINAL_PWD_TRX_MOTO			= "TERMINAL.PASSWORDOPTION.TRX.MOTO";
    public final static String CFGPATH_TERMINAL_PWD_TRX_BALINQUIRY		= "TERMINAL.PASSWORDOPTION.TRX.BALINQUIRY";
    public final static String CFGPATH_TERMINAL_PWD_TRX_CARDAUTH		= "TERMINAL.PASSWORDOPTION.TRX.CARDAUTH";
    public final static String CFGPATH_TERMINAL_PWD_TRX_BILLPAYMENT	= "TERMINAL.PASSWORDOPTION.TRX.BILLPAYMENT";
    public final static String CFGPATH_TERMINAL_PWD_TRX_REVERSAL		= "TERMINAL.PASSWORDOPTION.TRX.REVERSAL";
    public final static String CFGPATH_TERMINAL_PWD_TRX_REENTER		= "TERMINAL.PASSWORDOPTION.TRX.REENTER";

    // General
    public final static String CFGPATH_TERMINAL_LOCKSCREEN			= "TERMINAL.GENERAL.LOCKSCREEN";
    public final static String CFGPATH_TERMINAL_LANGUAGE_DEFAULT	= "TERMINAL.GENERAL.LANGUAGE.DEFAULT";
    public final static String CFGPATH_TERMINAL_LANGUAGE_SUPPORTED	= "TERMINAL.GENERAL.LANGUAGE.SUPPORTED";
    public final static String CFGPATH_TERMINAL_CURRENCYSYMBOL		= "TERMINAL.GENERAL.CURRENCYSYMBOL";
    public final static String CFGPATH_TERMINAL_DEMOMODE			= "TERMINAL.GENERAL.DEMOMODE";
    public final static String CFGPATH_TERMINAL_LOGO_IDLELOGO							= "TERMINAL.GENERAL.LOGO.IDLE";
    public final static String CFGPATH_TERMINAL_LOGO_SAMSUNGPAYLOGO_ENABLED			= "TERMINAL.GENERAL.LOGO.SAMSUNGPAY.ENABLED";
    public final static String CFGPATH_TERMINAL_LOGO_SAMSUNGPAYLOGO_LOCKSCREEN			= "TERMINAL.GENERAL.LOGO.SAMSUNGPAY.LOCKSCREEN";
    public final static String CFGPATH_TERMINAL_LOGO_SAMSUNGPAYLOGO_CARDENTRYSCREEN	= "TERMINAL.GENERAL.LOGO.SAMSUNGPAY.CARDENTRYSCREEN";

    // Terminal Timeouts
    public final static String CFGPATH_TERMINAL_MASTER_TIMEOUT		= "TERMINAL.TIMEOUT.MASTER";
    public final static String CFGPATH_TERMINAL_IDLE_TIMEOUT		= "TERMINAL.TIMEOUT.IDLE";
    public final static String CFGPATH_TERMINAL_INPUT_TIMEOUT		= "TERMINAL.TIMEOUT.INPUT";

    // EMV Options
    public final static String CFGPATH_TERMINAL_EMV_TERMTYPE			= "TERMINAL.EMVOPTION.TYPE";
    public final static String CFGPATH_TERMINAL_EMV_TERMCOUNTRYCODE	= "TERMINAL.EMVOPTION.COUNTRYCODE";
    public final static String CFGPATH_TERMINAL_EMV_TERMCURRENCYCODE	= "TERMINAL.EMVOPTION.CURRENCYCODE";
    public final static String CFGPATH_TERMINAL_EMV_TERMCURRENCYEXP	= "TERMINAL.EMVOPTION.CURRENCYEXP";
    public final static String CFGPATH_TERMINAL_EMV_TERMCAPABILITY		= "TERMINAL.EMVOPTION.CAPABILITY";
    public final static String CFGPATH_TERMINAL_EMV_TERMADDLCAPABILITY	= "TERMINAL.EMVOPTION.ADDLCAPABILITY";
    public final static String CFGPATH_TERMINAL_EMV_APPCAPABILITY		= "TERMINAL.EMVOPTION.APPCAPABILITY";
    public final static String CFGPATH_TERMINAL_EMV_EARLYAMTENTRY		= "TERMINAL.EMVOPTION.EARLYAMTENTRY";
    public final static String CFGPATH_TERMINAL_EMV_ALLOWPINBYPASS		= "TERMINAL.EMVOPTION.ALLOWPINBYPASS";
    public final static String CFGPATH_TERMINAL_EMV_PINRETRY			= "TERMINAL.EMVOPTION.PINRETRY";
    public final static String CFGPATH_TERMINAL_EMV_KERNELMODE			= "TERMINAL.EMVOPTION.EMVKERNELMODE";
    public final static String CFGPATH_TERMINAL_EMV_VISADEBITOPTIONOUT	= "TERMINAL.EMVOPTION.VISADEBITOPTIONOUT";
    public final static String CFGPATH_TERMINAL_EMV_MERCHCATCODE		= "TERMINAL.EMVOPTION.MERCHCATCODE";
    public final static String CFGPATH_TERMINAL_EMV_MERCHADDRESS		= "TERMINAL.EMVOPTION.MERCHADDRESS";

    // Tip Options
    public final static String CFGPATH_TERMINAL_TIP_ENABLED		= "TERMINAL.TIPOPTIONS.ENABLED";
    public final static String CFGPATH_TERMINAL_TIP_AMT1 			= "TERMINAL.TIPOPTIONS.AMOUNT1";
    public final static String CFGPATH_TERMINAL_TIP_AMT2 			= "TERMINAL.TIPOPTIONS.AMOUNT2";
    public final static String CFGPATH_TERMINAL_TIP_AMT3 			= "TERMINAL.TIPOPTIONS.AMOUNT3";
    public final static String CFGPATH_TERMINAL_TIP_PCT1 			= "TERMINAL.TIPOPTIONS.PERCENT1";
    public final static String CFGPATH_TERMINAL_TIP_PCT2 			= "TERMINAL.TIPOPTIONS.PERCENT2";
    public final static String CFGPATH_TERMINAL_TIP_PCT3 			= "TERMINAL.TIPOPTIONS.PERCENT3";
    public final static String CFGPATH_TERMINAL_TIP_EXCESSTIP 		= "TERMINAL.TIPOPTIONS.EXCESSTIP";
    public final static String CFGPATH_TERMINAL_TIP_FLOORPCT 		= "TERMINAL.TIPOPTIONS.FLOORPCT";

    // Terminal Processing Options
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_DCC			= "TERMINAL.PROCESSINGOPTION.DCC.ENABLED";
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_MCP			= "TERMINAL.PROCESSINGOPTION.MCP";
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_PANENCRYPT	= "TERMINAL.PROCESSINGOPTION.PANENCRYPTION"; 	//Note: PAN requires to be always encrypted
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_MANUALINVOICE = "TERMINAL.PROCESSINGOPTION.MANUALINVOICE";
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_SHIFT 		= "TERMINAL.PROCESSINGOPTION.SHIFT";
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_MULTIMERCHANT = "TERMINAL.PROCESSINGOPTION.MULTIMERCHANT";
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_OPERATORID  = "TERMINAL.PROCESSINGOPTION.OPERATORID.ENABLED";
    public final static String CFGPATH_TERMINAL_PROCOPT_OPERATORID_DEFAULT  = "TERMINAL.PROCESSINGOPTION.OPERATORID.DEFAULT";
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_TABLE  		= "TERMINAL.PROCESSINGOPTION.TABLE";
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_CASHBACK 	= "TERMINAL.PROCESSINGOPTION.CASHBACK";
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_CASHADV		= "TERMINAL.PROCESSINGOPTION.CASHADV";
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_TELLERID	= "TERMINAL.PROCESSINGOPTION.TELLERID";
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_STOREFWD	= "TERMINAL.PROCESSINGOPTION.STOREFWD";
    public final static String CFGPATH_TERMINAL_PROCOPT_ENABLE_EXPDATE		= "TERMINAL.PROCESSINGOPTION.EXPDATE";

    // Surcharge Entry Option
    public final static String  CFGPATH_TERMINAL_PROCOPT_SURCHARGE_ENABLE	= "TERMINAL.PROCESSINGOPTION.SURCHARGE.ENABLED";
    public final static String  CFGPATH_TERMINAL_PROCOPT_SURCHARGE_PERCENT	= "TERMINAL.PROCESSINGOPTION.SURCHARGE.PERCENT";

    // Tax Entry Option
    public final static String CFGPATH_TERMINAL_PROCOPT_TAX_ENABLE			= "TERMINAL.PROCESSINGOPTION.TAX.ENABLED";
    public final static String CFGPATH_TERMINAL_PROCOPT_TAX_PERCENT		= "TERMINAL.PROCESSINGOPTION.TAX.PERCENT";

    // Card Entry Retries
    public final static String  CFGPATH_TERMINAL_PROCOPT_CARDENTRYRETRIES = "TERMINAL.PROCESSINGOPTION.CARDENTRYRETRIES";

    // Partial Authorization
    public final static String  CFGPATH_TERMINAL_PROCOPT_PARTIALAUTH	= "TERMINAL.PROCESSINGOPTION.PARTIALAUTHORIZATION";

    // Terminal Operator Options
    public final static String  CFGPATH_TERMINAL_OPER_ENABLE_SIGNIN			= "TERMINAL.OPERATOR.ENABLE_SIGNIN";
    public final static String  CFGPATH_TERMINAL_OPER_SIGNED_IN_OPERID		= "TERMINAL.OPERATOR.SIGNED_IN.OPERATORID";
    public final static String  CFGPATH_TERMINAL_OPER_SIGNED_IN_PWENTERED	= "TERMINAL.OPERATOR.SIGNED_IN.PW_ENTERED";
    public final static String  CFGPATH_TERMINAL_OPER_COUNT					= "TERMINAL.OPERATOR.COUNT";
    public final static String  CFGPATH_TERMINAL_OPER_ROOT_TAG				= "TERMINAL.OPERATOR._%s";
    public final static String  CFGPATH_TERMINAL_OPER_OPERATOR_ID			= "TERMINAL.OPERATOR._%s.OPERATORID";
    public final static String  CFGPATH_TERMINAL_OPER_OPERATOR_NAME			= "TERMINAL.OPERATOR._%s.OPERATORNAME";
    public final static String  CFGPATH_TERMINAL_OPER_OPERATOR_PW			= "TERMINAL.OPERATOR._%s.PASSWORD";
    public final static String  CFGPATH_TERMINAL_OPER_OPERATOR_PWEXP		= "TERMINAL.OPERATOR._%s.PWDEXPIRE";
    public final static String  CFGPATH_TERMINAL_OPER_SEARCH_CFG			= "TERMINAL.OPERATOR.%s";
    public final static String  CFGPATH_TERMINAL_OPER_SEARCH_OPERATORID		= "TERMINAL.OPERATOR.%s.OPERATORID";
    public final static String  CFGPATH_TERMINAL_OPER_SEARCH_PASSWORD		= "TERMINAL.OPERATOR.%s.PASSWORD";

    // Receipt
    public final static String  CFGPATH_TERMINAL_RCPT_HEADER_LOGO			= "TERMINAL.RECEIPT.HEADER.LOGO";
    public final static String  CFGPATH_TERMINAL_RCPT_HEADER_LN1			= "TERMINAL.RECEIPT.HEADER.LN1";
    public final static String  CFGPATH_TERMINAL_RCPT_HEADER_LN2			= "TERMINAL.RECEIPT.HEADER.LN2";
    public final static String  CFGPATH_TERMINAL_RCPT_HEADER_LN3			= "TERMINAL.RECEIPT.HEADER.LN3";
    public final static String  CFGPATH_TERMINAL_RCPT_HEADER_LN4			= "TERMINAL.RECEIPT.HEADER.LN4";
    public final static String  CFGPATH_TERMINAL_RCPT_HEADER_LN5			= "TERMINAL.RECEIPT.HEADER.LN5";
    public final static String  CFGPATH_TERMINAL_RCPT_HEADER_LN6			= "TERMINAL.RECEIPT.HEADER.LN6";
    public final static String  CFGPATH_TERMINAL_RCPT_FOOTER_LOGO			= "TERMINAL.RECEIPT.FOOTER.LOGO";
    public final static String  CFGPATH_TERMINAL_RCPT_FOOTER_LN1			= "TERMINAL.RECEIPT.FOOTER.LN1";
    public final static String  CFGPATH_TERMINAL_RCPT_FOOTER_LN2			= "TERMINAL.RECEIPT.FOOTER.LN2";
    public final static String  CFGPATH_TERMINAL_RCPT_FOOTER_LN3			= "TERMINAL.RECEIPT.FOOTER.LN3";
    public final static String  CFGPATH_TERMINAL_RCPT_FOOTER_LN4			= "TERMINAL.RECEIPT.FOOTER.LN4";
    public final static String  CFGPATH_TERMINAL_RCPT_FOOTER_LN5			= "TERMINAL.RECEIPT.FOOTER.LN5";
    public final static String  CFGPATH_TERMINAL_RCPT_FOOTER_LN6			= "TERMINAL.RECEIPT.FOOTER.LN6";
    public final static String  CFGPATH_TERMINAL_RCPT_PAUSESECONDRECEIPT	= "TERMINAL.RECEIPT.PAUSESECONDRECEIPT";
    public final static String  CFGPATH_TERMINAL_RCPT_MERCHANTCOPY			= "TERMINAL.RECEIPT.MERCHANTCOPY";
    public final static String  CFGPATH_TERMINAL_RCPT_CUSTOMERCOPY			= "TERMINAL.RECEIPT.CUSTOMERCOPY";
    public final static String  CFGPATH_TERMINAL_RCPT_BANKCOPY				= "TERMINAL.RECEIPT.BANKCOPY";
    public final static String  CFGPATH_TERMINAL_RCPT_REPRINTCUSTOMERCOPY	= "TERMINAL.RECEIPT.REPRINTCUSTOMERCOPY";

    // TMS Host
    public final static String CFGPATH_TERMINAL_TMS_DEFACTIVEHOST		= "TERMINAL.TMSHOST.DEFAULTACTIVEHOST";
    public final static String CFGPATH_TERMINAL_TMS_HOSTCOUNT			= "TERMINAL.TMSHOST.COUNT";
    public final static String CFGPATH_TERMINAL_TMS_TMSID				= "TERMINAL.TMSHOST._%d.TMSID";
    public final static String CFGPATH_TERMINAL_TMS_IP_COUNT			= "TERMINAL.TMSHOST._%d.IP.COUNT";
    public final static String CFGPATH_TERMINAL_TMS_IP_ADDRESS			= "TERMINAL.TMSHOST._%d.IP._%d.IPADDRESS";
    public final static String CFGPATH_TERMINAL_TMS_IP_PORT			= "TERMINAL.TMSHOST._%d.IP._%d.PORT";
    public final static String CFGPATH_TERMINAL_TMS_IP_SSLENABLE		= "TERMINAL.TMSHOST._%d.IP._%d.SSL";
    public final static String CFGPATH_TERMINAL_TMS_IP_SSLMETHOD		= "TERMINAL.TMSHOST._%d.IP._%d.SSLMETHOD";
    public final static String CFGPATH_TERMINAL_TMS_IP_SSLCERT			= "TERMINAL.TMSHOST._%d.IP._%d.SSLCERT";
    public final static String CFGPATH_TERMINAL_TMS_IP_CLNTAUTH		= "TERMINAL.TMSHOST._%d.IP._%d.CLNTAUTH";
    public final static String CFGPATH_TERMINAL_TMS_IP_CLNTKEY			= "TERMINAL.TMSHOST._%d.IP._%d.CLNTKEY";
    public final static String CFGPATH_TERMINAL_TMS_IP_CLNTCERT		= "TERMINAL.TMSHOST._%d.IP._%d.CLNTCERT";
    public final static String CFGPATH_TERMINAL_TMS_IP_CLNTPWD			= "TERMINAL.TMSHOST._%d.IP._%d.CLNTPWD";
    public final static String CFGPATH_TERMINAL_TMS_DIAL_COUNT			= "TERMINAL.TMSHOST._%d.MODEM.COUNT";
    public final static String CFGPATH_TERMINAL_TMS_DIAL_NUMBER		= "TERMINAL.TMSHOST._%d.MODEM._%d.NUMBER";
    public final static String CFGPATH_TERMINAL_TMS_DIAL_PREFIX		= "TERMINAL.TMSHOST._%d.MODEM._%d.PREFIX";
    public final static String CFGPATH_TERMINAL_TMS_DIAL_MODE			= "TERMINAL.TMSHOST._%d.MODEM._%d.MODE";
    public final static String CFGPATH_TERMINAL_TMS_DIAL_BAUDRATE		= "TERMINAL.TMSHOST._%d.MODEM._%d.BAUDRATE";
    public final static String CFGPATH_TERMINAL_TMS_DIAL_DIALMODE		= "TERMINAL.TMSHOST._%d.MODEM._%d.DIALMODE";
    public final static String CFGPATH_TERMINAL_TMS_DIAL_USERNAME		= "TERMINAL.TMSHOST._%d.MODEM._%d.USERNAME";
    public final static String CFGPATH_TERMINAL_TMS_DIAL_PWD			= "TERMINAL.TMSHOST._%d.MODEM._%d.PWD";

    // SNF
    public final static String CFGPATH_TERMINAL_SNF_ENABLED 				= "TERMINAL.SNF.ENABLED";
    public final static String CFGPATH_TERMINAL_SNF_MODE					= "TERMINAL.SNF.MODE";
    public final static String CFGPATH_TERMINAL_SNF_LIMIT_PERBRAND 		= "TERMINAL.SNF.LIMIT.PERBRAND";
    public final static String CFGPATH_TERMINAL_SNF_LIMIT_FLOOR			= "TERMINAL.SNF.LIMIT.FLOOR";
    public final static String CFGPATH_TERMINAL_SNF_LIMIT_MAXCUMULATIVE	= "TERMINAL.SNF.LIMIT.MAXCUMULATIVE";
    public final static String CFGPATH_TERMINAL_SNF_LIMIT_MAXSNFCOUNT			= "TERMINAL.SNF.LIMIT.MAXSNFCOUNT";

    public final static String CFGPATH_TERMINAL_SNF_EMV_TVR_MASK			= "TERMINAL.SNF.EMV.TVR_MASK";
    public final static String CFGPATH_TERMINAL_SNF_EMV_TSI_MASK			= "TERMINAL.SNF.EMV.TSI_MASK";


    //1 COMMUNICATIONS PARAMETERS

    // Media, pre-dial, pre-print
    public final static String CFGPATH_COMMS_MEDIA				= "COMMUNICATIONS.MEDIA";
    public final static String CFGPATH_COMMS_PREDIALENABLE		= "COMMUNICATIONS.PREDIAL";
    public final static String CFGPATH_COMMS_PREPRINTENABLE	= "COMMUNICATIONS.PREPRINT";

    // GPRS Info
    public final static String CFGPATH_COMMS_GPRS_APN			= "COMMUNICATIONS.GPRSINFO.SIM%d.APN";
    public final static String CFGPATH_COMMS_GPRS_UID			= "COMMUNICATIONS.GPRSINFO.SIM%d.UID";
    public final static String CFGPATH_COMMS_GPRS_PWD			= "COMMUNICATIONS.GPRSINFO.SIM%d.PWD";
    public final static String CFGPATH_COMMS_GPRS_SIMPIN		= "COMMUNICATIONS.GPRSINFO.SIM%d.SIMPIN";
    public final static String CFGPATH_COMMS_GPRS_DNS			= "COMMUNICATIONS.GPRSINFO.SIM%d.DNS";
    public final static String CFGPATH_COMMS_GPRS_PHONE		= "COMMUNICATIONS.GPRSINFO.SIM%d.PHONE";

    // Comms Timeouts
    public final static String CFGPATH_COMMS_TIMEOUT_CONN_ETH		= "COMMUNICATIONS.TIMEOUT.CONNECT.ETH";
    public final static String CFGPATH_COMMS_TIMEOUT_CONN_DIAL		= "COMMUNICATIONS.TIMEOUT.CONNECT.MODEM";
    public final static String CFGPATH_COMMS_TIMEOUT_CONN_GPRS		= "COMMUNICATIONS.TIMEOUT.CONNECT.GPRS";
    public final static String CFGPATH_COMMS_TIMEOUT_RECV_ETH		= "COMMUNICATIONS.TIMEOUT.RECEIVE.ETH";
    public final static String CFGPATH_COMMS_TIMEOUT_RECV_DIAL		= "COMMUNICATIONS.TIMEOUT.RECEIVE.MODEM";
    public final static String CFGPATH_COMMS_TIMEOUT_RECV_GPRS		= "COMMUNICATIONS.TIMEOUT.RECEIVE.GPRS";


    //1 INTERNAL CONFIGURATIONS/VARIABLES

    public final static String CFGPATH_INTERNAL_TRACENUMBER		= "INTERNAL.TRACENUMBER";
    public final static String CFGPATH_INTERNAL_TRANSEQNUMBER		= "INTERNAL.TRANSEQNUMBER";
    public final static String CFGPATH_INTERNAL_INVOICENUMBER		= "INTERNAL.INVOICENUMBER";
    public final static String CFGPATH_INTERNAL_BATCHNUMBER		= "INTERNAL.BATCHNUMBER";
    public final static String CFGPATH_INTERNAL_EMVTRANSNUMBER		= "INTERNAL.EMVTRANSNUMBER";
    public final static String CFGPATH_INTERNAL_GEN2KEY			= "INTERNAL.GEN2KEY";
    public final static String CFGPATH_INTERNAL_SNF_TOTALSNFCOUNT	= "INTERNAL.SNF.TOTALSNFCOUNT";
    public final static String CFGPATH_INTERNAL_SNF_TOTALCUMULATIVE = "INTERNAL.SNF.TOTALCUMULATIVE";


    //1 CAPK LIST

    public final static String CFGPATH_CAPK_COUNT		= "CAPKLIST.COUNT";
    public final static String CFGPATH_CAPK_RID		= "CAPKLIST._%d.RID";
    public final static String CFGPATH_CAPK_INDEX		= "CAPKLIST._%d.INDEX";
    public final static String CFGPATH_CAPK_MODULUS	= "CAPKLIST._%d.MODULUS";
    public final static String CFGPATH_CAPK_EXPONENT	= "CAPKLIST._%d.EXPONENT";
    public final static String CFGPATH_CAPK_EXPDATE	= "CAPKLIST._%d.EXPDATE";
    public final static String CFGPATH_CAPK_CHECKSUM	= "CAPKLIST._%d.CHECKSUM";


    //1 CARD BIN RANGE

    public final static String CFGPATH_CARDBIN_COUNT		= "CARDBINS.COUNT";
    public final static String CFGPATH_CARDBIN_LOW			= "CARDBINS.RANGE_%d.LOW";
    public final static String CFGPATH_CARDBIN_HIGH		= "CARDBINS.RANGE_%d.HIGH";
    public final static String CFGPATH_CARDBIN_MAXLENGTH	= "CARDBINS.RANGE_%d.MAX";
    public final static String CFGPATH_CARDBIN_MINLENGTH	= "CARDBINS.RANGE_%d.MIN";
    public final static String CFGPATH_CARDBIN_CARDTYPE	= "CARDBINS.RANGE_%d.CARDTYPE";


    //1 ISSUER INFORMATION

    // Generic Info
    public final static String CFGPATH_ISS_COUNT			= "ISSINFO.COUNT";
    public final static String CFGPATH_ISS_NAME			= "ISSINFO.ISS_%d.NAME";
    public final static String CFGPATH_ISS_PINSUPPORT		= "ISSINFO.ISS_%d.PIN";
    public final static String CFGPATH_ISS_MAXPINLEN		= "ISSINFO.ISS_%d.MAXPINLEN";
    public final static String CFGPATH_ISS_PINLEN			= "ISSINFO.ISS_%d.PINLEN";
    public final static String CFGPATH_ISS_FALLBACKALLOWED	= "ISSINFO.ISS_%d.FALLBACKALLOWED";
    public final static String CFGPATH_ISS_SIGNREQUIRED	= "ISSINFO.ISS_%d.SIGNREQUIRED";
    public final static String CFGPATH_ISS_PANMASKENABLED	= "ISSINFO.ISS_%d.PANMASKENABLED";

    //SnF Limit
    public final static String CFGPATH_ISS_SNF_FLOORLIMIT	= "ISSINFO.ISS_%d.SNF.LIMIT.FLOOR";

    // Limit
    public final static String CFGPATH_ISS_FLOORLIMIT		= "ISSINFO.ISS_%d.LIMIT.FLOOR";
    public final static String CFGPATH_ISS_CTLSSIGNLIMIT	= "ISSINFO.ISS_%d.LIMIT.CTLSSIGN";
    public final static String CFGPATH_ISS_CASHBACKLIMIT	= "ISSINFO.ISS_%d.LIMIT.CASHBACK";

    // Fee
    public final static String CFGPATH_ISS_MERCHANTFEE		= "ISSINFO.ISS_%d.FEE.MERCHANT";
    public final static String CFGPATH_ISS_CASHBACKFEE		= "ISSINFO.ISS_%d.FEE.CASHBACK";

    // Moto
    public final static String CFGPATH_ISS_ENABLE_MOTO					= "ISSINFO.ISS_%d.MOTO.ENABLED";
    public final static String CFGPATH_ISS_ENABLE_PROMPTPURCHORDER		= "ISSINFO.ISS_%d.MOTO.PROMPTPURCHORDER";

    // Transaction
    public final static String CFGPATH_ISS_ENABLE_REFUND			= "ISSINFO.ISS_%d.TRANSACTION.REFUND";
    public final static String CFGPATH_ISS_ENABLE_VOID				= "ISSINFO.ISS_%d.TRANSACTION.VOID";
    public final static String CFGPATH_ISS_ENABLE_AUTH				= "ISSINFO.ISS_%d.TRANSACTION.AUTH";
    public final static String CFGPATH_ISS_ENABLE_ADJUST			= "ISSINFO.ISS_%d.TRANSACTION.ADJUST";
    public final static String CFGPATH_ISS_ENABLE_AUTHCOMPLETION	= "ISSINFO.ISS_%d.TRANSACTION.AUTHCOMPLETION";
    public final static String CFGPATH_ISS_ENABLE_OFFLINE			= "ISSINFO.ISS_%d.TRANSACTION.OFFLINE";
    public final static String CFGPATH_ISS_ENABLE_EBT				= "ISSINFO.ISS_%d.TRANSACTION.EBT";

    // Processing
    public final static String CFGPATH_ISS_ENABLE_CASHBACK				= "ISSINFO.ISS_%d.PROCESSING.CASHBACK";
    public final static String CFGPATH_ISS_ENABLE_MANUALENTRY			= "ISSINFO.ISS_%d.PROCESSING.MANUALENTRY";
    public final static String CFGPATH_ISS_ENABLE_CARDPRESENT			= "ISSINFO.ISS_%d.PROCESSING.CARDPRESENT";
    public final static String CFGPATH_ISS_ENABLE_CARDIMPRINT			= "ISSINFO.ISS_%d.PROCESSING.CARDIMPRINT";
    public final static String CFGPATH_ISS_ENABLE_MOD10CHECK			= "ISSINFO.ISS_%d.PROCESSING.MOD10CHECK";
    public final static String CFGPATH_ISS_ENABLE_VERIFYLAST4DIGIT		= "ISSINFO.ISS_%d.PROCESSING.VERIFYLAST4DIGIT";
    public final static String CFGPATH_ISS_ENABLE_IGNORETRACK1			= "ISSINFO.ISS_%d.PROCESSING.IGNORETRACK1";
    public final static String CFGPATH_ISS_ENABLE_VERIFYCVV2			= "ISSINFO.ISS_%d.PROCESSING.VERIFYCVV2";

    // Address Verification System
    public final static String CFGPATH_ISS_ENABLE_AVS				= "ISSINFO.ISS_%d.AVS.ENABLED";
    public final static String CFGPATH_ISS_ENABLE_PROMPTADDRESS	= "ISSINFO.ISS_%d.AVS.PROMPTADDRESS";
    public final static String CFGPATH_ISS_ENABLE_PROMPTZIPCODE	= "ISSINFO.ISS_%d.AVS.PROMPTZIPCODE";

    // EMV AID Parameters
    public final static String CFGPATH_ISS_EMV_AIDCOUNT					= "ISSINFO.ISS_%d.EMV.AIDSUPP.COUNT";
    public final static String CFGPATH_ISS_EMV_AID							= "ISSINFO.ISS_%d.EMV.AIDSUPP._%d.AID";
    public final static String CFGPATH_ISS_EMV_CARDTYPE					= "ISSINFO.ISS_%d.EMV.AIDSUPP._%d.CARDTYPE";
    public final static String CFGPATH_ISS_EMV_PINBYPASS					= "ISSINFO.ISS_%d.EMV.AIDSUPP._%d.PINBYPASS";
    public final static String CFGPATH_ISS_EMV_CVMLIMIT					= "ISSINFO.ISS_%d.EMV.AIDSUPP._%d.CVMLIMIT";
    public final static String CFGPATH_ISS_EMV_NOCVMLIMIT					= "ISSINFO.ISS_%d.EMV.AIDSUPP._%d.NOCVMLIMIT";


    //1 ACQUIRER INFORMATION

    //  Acquirer Generic Information
    public final static String CFGPATH_ACQS_COUNT					= "ACQS.COUNT";
    public final static String CFGPATH_ACQS_DEFAULTACTIVESET		= "ACQS.DEFAULTACTIVESET";
    public final static String CFGPATH_ACQS_INFO_NAME				= "ACQS._%d.NAME";
    public final static String CFGPATH_ACQS_INFO_NII				= "ACQS._%d.ACQINFO.NII";
    public final static String CFGPATH_ACQS_INFO_TERMINALID		= "ACQS._%d.ACQINFO.TERMINALID";
    public final static String CFGPATH_ACQS_INFO_MERCHANTID		= "ACQS._%d.ACQINFO.MERCHANTID";
    public final static String CFGPATH_ACQS_INFO_SECONDARYID		= "ACQS._%d.ACQINFO.SECONDARYID";
    public final static String CFGPATH_ACQS_INFO_GATEWAYTID		= "ACQS._%d.ACQINFO.GATEWAYTID";
    public final static String CFGPATH_ACQS_INFO_GATEWAYMID		= "ACQS._%d.ACQINFO.GATEWAYMID";
    public final static String CFGPATH_ACQS_INFO_IGNOREHOSTTIME	= "ACQS._%d.ACQINFO.IGNOREHOSTTIME";
    public final static String CFGPATH_ACQS_INFO_REMOVEPREAUTH		= "ACQS._%d.ACQINFO.REMOVEPREAUTH";

    // Security Information
    public final static String CFGPATH_ACQS_SEC_PINFORMAT			= "ACQS._%d.SECURITY.PINFORMAT";
    public final static String CFGPATH_ACQS_SEC_PINLEN				= "ACQS._%d.SECURITY.PINLEN";
    public final static String CFGPATH_ACQS_SEC_MKEY_PIN_TYPE		= "ACQS._%d.SECURITY.MKEY.PIN.TYPE";
    public final static String CFGPATH_ACQS_SEC_MKEY_PIN_INDEX		= "ACQS._%d.SECURITY.MKEY.PIN.INDEX";
    public final static String CFGPATH_ACQS_SEC_MKEY_PIN_KEY		= "ACQS._%d.SECURITY.MKEY.PIN.KEY";
    public final static String CFGPATH_ACQS_SEC_MKEY_PIN_IKSN		= "ACQS._%d.SECURITY.MKEY.PIN.IKSN";
    public final static String CFGPATH_ACQS_SEC_MKEY_MAC_TYPE		= "ACQS._%d.SECURITY.MKEY.MAC.TYPE";
    public final static String CFGPATH_ACQS_SEC_MKEY_MAC_INDEX		= "ACQS._%d.SECURITY.MKEY.MAC.INDEX";
    public final static String CFGPATH_ACQS_SEC_MKEY_MAC_KEY		= "ACQS._%d.SECURITY.MKEY.MAC.KEY";
    public final static String CFGPATH_ACQS_SEC_MKEY_MAC_IKSN		= "ACQS._%d.SECURITY.MKEY.MAC.IKSN";
    public final static String CFGPATH_ACQS_SEC_MKEY_DATA_TYPE		= "ACQS._%d.SECURITY.MKEY.DATA.TYPE";
    public final static String CFGPATH_ACQS_SEC_MKEY_DATA_INDEX	= "ACQS._%d.SECURITY.MKEY.DATA.INDEX";
    public final static String CFGPATH_ACQS_SEC_MKEY_DATA_KEY		= "ACQS._%d.SECURITY.MKEY.DATA.KEY";
    public final static String CFGPATH_ACQS_SEC_MKEY_DATA_IKSN		= "ACQS._%d.SECURITY.MKEY.DATA.IKSN";
    public final static String CFGPATH_ACQS_SEC_WKEY_PIN_INDEX		= "ACQS._%d.SECURITY.WKEY.PIN.INDEX";
    public final static String CFGPATH_ACQS_SEC_WKEY_PIN_KEY		= "ACQS._%d.SECURITY.WKEY.PIN.KEY";
    public final static String CFGPATH_ACQS_SEC_WKEY_MAC_INDEX		= "ACQS._%d.SECURITY.WKEY.MAC.INDEX";
    public final static String CFGPATH_ACQS_SEC_WKEY_MAC_KEY		= "ACQS._%d.SECURITY.WKEY.MAC.KEY";
    public final static String CFGPATH_ACQS_SEC_WKEY_DATA_INDEX	= "ACQS._%d.SECURITY.WKEY.DATA.INDEX";
    public final static String CFGPATH_ACQS_SEC_WKEY_DATA_KEY		= "ACQS._%d.SECURITY.WKEY.DATA.KEY";
    public final static String CFGPATH_ACQS_SEC_ENABLE_DATAENCRYPTION	= "ACQS._%d.SECURITY.DATAENCRYPTIONENABLE";
    public final static String CFGPATH_ACQS_SEC_DATATAGS			= "ACQS._%d.SECURITY.DATATAGS";

    // Issuer Index Information
    public final static String CFGPATH_ACQS_ISS_COUNT			= "ACQS._%d.ISSUER.COUNT";
    public final static String CFGPATH_ACQS_ISS_INFO_IDX		= "ACQS._%d.ISSUER._%d.ISSINFO";
    public final static String CFGPATH_ACQS_ISS_BINRANGE_COUNT = "ACQS._%d.ISSUER._%d.BINRANGES.COUNT";
    public final static String CFGPATH_ACQS_ISS_BINRANGE_IDX 	= "ACQS._%d.ISSUER._%d.BINRANGES._%d";

    // Generic Host Information
    public final static String CFGPATH_ACQS_HOST_DEFAULTACTIVE		= "ACQS._%d.HOST.DEFAULTACTIVEHOST";
    public final static String CFGPATH_ACQS_HOST_COUNT				= "ACQS._%d.HOST.COUNT";
    public final static String CFGPATH_ACQS_HOST_USEDIALBACKUP		= "ACQS._%d.HOST._%d.USEDIALBACKUP";
    public final static String CFGPATH_ACQS_HOST_CONNRETRY_TOTAL	= "ACQS._%d.HOST._%d.CONNECT_RETRY.TOTAL";
    public final static String CFGPATH_ACQS_HOST_CONNRETRY_PERLINE	= "ACQS._%d.HOST._%d.CONNECT_RETRY.PERLINE";

    // Host for Transaction or Settleent
    public final static String CFGPATH_ACQS_HOST_IP_COUNT		= "ACQS._%d.HOST._%d.%s.IP.COUNT";
    public final static String CFGPATH_ACQS_HOST_IP_ADDRESS	= "ACQS._%d.HOST._%d.%s.IP._%d.IPADDRESS";
    public final static String CFGPATH_ACQS_HOST_IP_PORT		= "ACQS._%d.HOST._%d.%s.IP._%d.PORT";
    public final static String CFGPATH_ACQS_HOST_IP_SSLENABLE	= "ACQS._%d.HOST._%d.%s.IP._%d.SSL";
    public final static String CFGPATH_ACQS_HOST_IP_SSLMETHOD	= "ACQS._%d.HOST._%d.%s.IP._%d.SSLMETHOD";
    public final static String CFGPATH_ACQS_HOST_IP_SSLCERT	= "ACQS._%d.HOST._%d.%s.IP._%d.SSLCERT";
    public final static String CFGPATH_ACQS_HOST_IP_CLNTAUTH	= "ACQS._%d.HOST._%d.%s.IP._%d.CLNTAUTH";
    public final static String CFGPATH_ACQS_HOST_IP_CLNTKEY	= "ACQS._%d.HOST._%d.%s.IP._%d.CLNTKEY";
    public final static String CFGPATH_ACQS_HOST_IP_CLNTCERT	= "ACQS._%d.HOST._%d.%s.IP._%d.CLNTCERT";
    public final static String CFGPATH_ACQS_HOST_IP_CLNTPWD	= "ACQS._%d.HOST._%d.%s.IP._%d.CLNTPWD";
    public final static String CFGPATH_ACQS_HOST_DIAL_COUNT	= "ACQS._%d.HOST._%d.%s.MODEM.COUNT";
    public final static String CFGPATH_ACQS_HOST_DIAL_NUMBER	= "ACQS._%d.HOST._%d.%s.MODEM._%d.NUMBER";
    public final static String CFGPATH_ACQS_HOST_DIAL_PREFIX	= "ACQS._%d.HOST._%d.%s.MODEM._%d.PREFIX";
    public final static String CFGPATH_ACQS_HOST_DIAL_MODE		= "ACQS._%d.HOST._%d.%s.MODEM._%d.MODE";
    public final static String CFGPATH_ACQS_HOST_DIAL_BAUDRATE	= "ACQS._%d.HOST._%d.%s.MODEM._%d.BAUDRATE";
    public final static String CFGPATH_ACQS_HOST_DIAL_DIALMODE	= "ACQS._%d.HOST._%d.%s.MODEM._%d.DIALMODE";


    //1 demo Specific Configurations

    // demo Assigned
    public final static String CFGPATH_demo_DEVELOPER_ID		= "demo.DEVELOPERID";
    public final static String CFGPATH_demo_VERSION_ID			= "demo.VERSIONID";
    public final static String CFGPATH_demo_TERMINAL_ID		= "demo.TERMINALID";
    public final static String CFGPATH_demo_MERCHANT_ID		= "demo.MERCHANTID";
    public final static String CFGPATH_demo_ACQUIRER_BIN		= "demo.ACQUIRERBIN";
    public final static String CFGPATH_demo_MERCH_CAT_CODE		= "demo.MERCHANTCATCODE";
    public final static String CFGPATH_demo_AGENT_BANK_NUMBER	= "demo.AGENTBANKNUMBER";
    public final static String CFGPATH_demo_AGENT_CHAIN_NUMBER	= "demo.AGENTCHAINNUMBER";
    public final static String CFGPATH_demo_STORE_NUMBER		= "demo.STORENUMBER";
    public final static String CFGPATH_demo_TERMINAL_NUMBER	= "demo.TERMINALNUMBER";
    public final static String CFGPATH_demo_HOSTMSGID			= "demo.HOSTMSGID";
    public final static String CFGPATH_demo_AUTHFACTOR1		= "demo.AUTHFACTOR1";

    // Terminal Specific
    public final static String CFGPATH_demo_DEVICE_CODE		= "demo.DEVICECODE";
    public final static String CFGPATH_demo_INDUSTRY_CODE		= "demo.INDUSTRYCODE";
    public final static String CFGPATH_demo_CITY_CODE			= "demo.CITYCODE";
    public final static String CFGPATH_demo_TIMEZONE_DIFF		= "demo.TIMEZONEDIFF";
    public final static String CFGPATH_demo_GATEWAY_ID			= "demo.GATEWAYID";
    public final static String CFGPATH_demo_APPLICATION_TYPE	= "demo.APPLICATIONTYPE";
    public final static String CFGPATH_demo_CURRENCY_CODE 		= CFGPATH_TERMINAL_EMV_TERMCURRENCYCODE;
    public final static String CFGPATH_demo_COUNTRY_CODE		= CFGPATH_TERMINAL_EMV_TERMCOUNTRYCODE;

    // Card Acceptor (Merchant) Data
    public final static String CFGPATH_demo_MERCHANT_NAME		= "demo.MERCHANTNAME";
    public final static String CFGPATH_demo_MERCHANT_CITY		= "demo.MERCHANTCITY";
    public final static String CFGPATH_demo_MERCHANT_STATE		= "demo.MERCHANTSTATE";
    public final static String CFGPATH_demo_MERCHANTPURCHASEID	= "demo.MERCHANTPURCHASEID";

    // EBT Parameters
    public final static String CFGPATH_demo_MERCH_ABA_NUMBER			= "demo.MERCHABANUMBER";
    public final static String CFGPATH_demo_MERCH_SETTLE_AGENT_NUMBER	= "demo.MERCHSETTLEAGENTNUMBER";
    public final static String CFGPATH_demo_RIID						= "demo.RIID";
    public final static String CFGPATH_demo_SHARING_GROUP_DEBIT		= "demo.SHARINGGROUP.DEBIT";
    public final static String CFGPATH_demo_SHARING_GROUP_EBT			= "demo.SHARINGGROUP.EBT";

    // Settlement Parameters
    public final static String CFGPATH_demo_CARDH_SVC_PHONE_NUM		= "demo.CARDHOLDERSVCPHONENUM";
    public final static String CFGPATH_demo_MERCHANT_LOCATION_NUM		= "demo.MERCHANTLOCATIONNUMBER";
}