/*
* This file was auto generated by buildconfig.py
* Don't modify!
* Generated time: 2017-11-18 16:10:36
*/
#ifndef _BUILD_CONFIG_H_
#define _BUILD_CONFIG_H_

#define RC_CONSOLE 1
#define BUILD_WITH_FASTBOOT 1
#define DENCRYPT_PIN_DATA 1
#define ERASE_KEY 1
#define SP_UPDATE_VERIFY_HASH 1
#define POSVERIFY_VENDOR 1
#define SET_GOOGLEPINYIN_DEFAULT 1

#endif