/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pos_device_QPboc_QPbocNative */

#ifndef _Included_com_pos_device_QPboc_QPbocNative
#define _Included_com_pos_device_QPboc_QPbocNative
#ifdef __cplusplus
extern "C" {
#endif

int regQPbocMethods(JNIEnv *env);

void unRegQPbocMethods(JNIEnv *env);

#ifdef __cplusplus
}
#endif
#endif

