/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pos_device_emv_EmvNative */

#ifndef _Included_com_pos_device_emv_EmvNative
#define _Included_com_pos_device_emv_EmvNative
#ifdef __cplusplus
extern "C" {
#endif

int regEmvMethods();

void unRegEmvMethods();

#ifdef __cplusplus
}
#endif
#endif
