/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andpos_AuthSignNative */

#ifndef _Included_com_andpos_AuthSignNative
#define _Included_com_andpos_AuthSignNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andpos_AuthSignNative
 * Method:    isUMS
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_com_andpos_AuthSignNative_isUMS
//  (JNIEnv *, jclass);

/*
 * Class:     com_andpos_AuthSignNative
 * Method:    isPCI
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_com_andpos_AuthSignNative_isPCI
//  (JNIEnv *, jclass);

/*
 * Class:     com_andpos_AuthSignNative
 * Method:    isDevelopment
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_com_andpos_AuthSignNative_isDevelopment
//  (JNIEnv *, jclass);
  
/*
 * Class:     com_andpos_AuthSignNative
 * Method:    getCert
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andpos_AuthSignNative_getCert
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
